
---
title: "projects"
description: |
output:
  postcards::solana
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(postcards)
```
**Prinicipal Investigator**

- **VALPRO**
<p style="text-align:justify;">The randomized-controlled trial tested whether the combination of valproic acid with fear memory retrieval before standard exposure enhances the treatment outcome for patients with fear of spiders. Key collaborating partners were [Prof. Dr. Johannes Gräff](https://people.epfl.ch/johannes.graeff?lang=en), the clinic director of the Psychiatric University Clinics Basel [Prof. Dr. Undine Lang](https://www.upk.ch/ueber-uns/klinikportrait/leitungspersonen/detail/team/lang-undine) and [Prof. Dr. Dominique de Quervain](https://mcn.unibas.ch/de/personen/dominique-de-quervain/). Click here for the preregristration on [ClinicalTrials.gov](https://clinicaltrials.gov/study/NCT02789813?locStr=Basel,%20Switzerland&country=Switzerland&state=Basel%20City&city=Basel&term=Phobia&rank=3) and [first results](https://link.springer.com/article/10.1007/s00702-023-02717-3). The research report is currently under peer review, check out later for updates.<p style="text-align:justify;">
 
 - *Hypothalamic-pituitary-adrenal axis functioning in anxiety disorders*
<p style="text-align:justify;">With a meta-analytic approach, we summarize the current state of research on the functionality of the hypothalamic-pituitary-adrenal axis in anxiety disorders. Key collaborating partner is [Dr. Susanne Fischer](https://www.psychologie.uzh.ch/de/bereiche/hea/klipsypt/team/susannefischer.html) from the University of Zurich. Click here for the [PROSPERO](https://www.crd.york.ac.uk/prospero/display_record.php?RecordID=284955) preregistration.<p style="text-align:justify;">

- *Hormones, conduct disorder, and callous-unemotional traits*
<p style="text-align:justify;">With a meta-analytic approach, we investigate the relationships between hormones and callous-unemotional traits, as well as conduct disorder, in children and adolescents. Co-Principal investigator is [Dr. Loreen Tisdall](https://psychologie.unibas.ch/de/personen/loreen-tisdall/) form the University of Basel. Click here for the [PROSPERO](https://www.crd.york.ac.uk/prospero/display_record.php?RecordID=428686) preregistration.<p style="text-align:justify;">

- *Common triggers of contamination obsessive-compulsive symptoms*
<p style="text-align:justify;">In the project we collected common triggers of contamination obsessive-compulsive symptoms (OCS) in a large Swiss population, along with the trigger severity, as well as the intensity of the obsessive-compulsive symptoms. We analyzed the collected information with an approach using large language models, and generated a map of OCS triggers by assessing their similarity through embeddings. Key collaborating partner is [Dr. Dirk Wulff](https://www.mpib-berlin.mpg.de/person/93374/2537) from the Max Planck Institute for Human Development, Berlin, Germany.<p style="text-align:justify;"> 

- *Mental representations of contamination obsessive-compulsive triggers*
<p style="text-align:justify;">The project aims to characterize contamination obsessive-compulsive stimuli based on theoretically guided dimensions as well as data-driven dimensions. Methodologically, similarity judgment is used to identify underlying dimensions, which are then analyzed using multidimensional scaling. The results have the potential to guide the development of new treatment approaches. Key collaborating partner is [Dr. Filip Melinscak](https://www.filipmelinscak.com) and the clinic director of the Psychiatric Hospital [PD Dr. Steffi Weidt](https://www.psychiatrie-sg.ch/unsere-fachpersonen/fachpersonen-detail/steffi-weidt).<p style="text-align:justify;"> 



**Co-investigator**

- **OCD-Detect**
<p style="text-align:justify;">The project investigates the feasibility and acceptance of the use of a wearable for automatic detection of compulsive hand-washing in a clinical population with obsessive-compulsive disorder. Principal investigator of the project is [PD. Dr. Karina Wahl](https://psychologie.unibas.ch/de/personen/karina-wahl/) from the University of Basel.<p style="text-align:justify;"> 

